name: Upload Reports - Cron

on:
 schedule:
   - cron:  "55 * * * *"
# on: workflow_dispatch

jobs:
  upload-reports:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt

    - name: Test
      uses: nuuuwan/python-repo-test@v1

    - name: Run - Upload
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        python workflows/upload_reports.py

    - name: Checkout repo branch data
      uses: actions/checkout@v3
      with:
        repository: 'nuuuwan/news_lk3_data'
        token: "${{ secrets.REPO_TOKEN }}"
        ref: "main"

    - name: Copy data, and push to repo branch data
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        
        cp -r /tmp/news_lk3_data/* .
        git add .
        git commit -m "Uploaded reports"

        git push origin main
